# Generated by Django 4.1.4 on 2022-12-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default='2323'),
            preserve_default=False,
        ),
    ]
