# Generated by Django 4.1.4 on 2022-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='qwwe', max_length=250),
            preserve_default=False,
        ),
    ]
